Configure nix toolbox

diff --git a/ide2/bin/ide2 b/ide2/bin/ide2
--- a/ide2/bin/ide2
+++ b/ide2/bin/ide2
@@ -5,4 +5,39 @@ set -euo pipefail
 TZ=$(timedatectl show --property=Timezone --value)
 export TZ
 
-docker compose -f "$(dirname "$0")/../docker-compose.yml" run --rm ide2
+PS3='Please enter your choice: '
+options=("base" "go" "lua" "rust" "php" "python" "webdev" "Quit")
+select opt in "${options[@]}"; do
+	case $opt in
+	"base")
+		break
+		;;
+	"go")
+		break
+		;;
+	"lua")
+		break
+		;;
+	"rust")
+		break
+		;;
+	"php")
+		break
+		;;
+	"python")
+		break
+		;;
+	"webdev")
+		break
+		;;
+	"Quit")
+		break
+		;;
+	*)
+		echo "invalid option $REPLY"
+		exit 1
+		;;
+	esac
+done
+
+docker compose -f "$(dirname "$0")/../docker-compose.yml" run --rm "ide2-$opt"
